// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-BbDRQzAk5vIz6AAct5Un8Sa9XliEkc',
    appId: '1:1090384398970:web:47956659211f2fe7a289c3',
    messagingSenderId: '1090384398970',
    projectId: 'nowly-b63e7',
    authDomain: 'nowly-b63e7.firebaseapp.com',
    storageBucket: 'nowly-b63e7.firebasestorage.app',
    measurementId: 'G-D43Z9R6RFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKiyoi-6qcjFjo8OJuk7IQjEH9prtnUU',
    appId: '1:1090384398970:android:3640e7475b5fdc44a289c3',
    messagingSenderId: '1090384398970',
    projectId: 'nowly-b63e7',
    storageBucket: 'nowly-b63e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BRYmOIE85UNBVGRECykbukAIs9Vxkug',
    appId: '1:1090384398970:ios:be34e2ebcc11a2f1a289c3',
    messagingSenderId: '1090384398970',
    projectId: 'nowly-b63e7',
    storageBucket: 'nowly-b63e7.firebasestorage.app',
    iosBundleId: 'com.diogosales.nowly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BRYmOIE85UNBVGRECykbukAIs9Vxkug',
    appId: '1:1090384398970:ios:004f7fc1f4a8a481a289c3',
    messagingSenderId: '1090384398970',
    projectId: 'nowly-b63e7',
    storageBucket: 'nowly-b63e7.firebasestorage.app',
    iosBundleId: 'com.example.nowly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp-BbDRQzAk5vIz6AAct5Un8Sa9XliEkc',
    appId: '1:1090384398970:web:b7be85f1a6f93a6da289c3',
    messagingSenderId: '1090384398970',
    projectId: 'nowly-b63e7',
    authDomain: 'nowly-b63e7.firebaseapp.com',
    storageBucket: 'nowly-b63e7.firebasestorage.app',
    measurementId: 'G-1GY7FN0LP3',
  );

}